name: spectacle.js
description: Build slides made with spectacle.js and upload the artifact!
inputs:
  path:
    description: Path to the root directory of the slideshow
    required: true

outputs:
  artifact:
    description: The artifact key that can be used to download it and recombine it into the built site

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Get yarn cache directory path
      working-directory: src/${{ inputs.path }}
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
    - name: Yarn cache
      working-directory: src/${{ inputs.path }}
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarnv1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarnv1-
    - name: Install Yarn Dependencies
      working-directory: src/${{ inputs.path }}
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Slides cache
      working-directory: src/${{ inputs.path }}
      uses: actions/cache@v3
      id: slides-cache
      with:
        path: dist
        key: ${{ runner.os }}-slides-${{ inputs.path }}-${{ hashFiles('./**/*') }}
        restore-keys: |
          ${{ runner.os }}-slidesv1-
    - name: Build Slides
      working-directory: src/${{ inputs.path }}
      if: ${{ steps.slides-cache.outputs.cache-hit != 'true' }}
      run: npm run build && mv dist ${{ inputs.path }}
      shell: bash
    - name: Upload Artifact
      working-directory: src/${{ inputs.path }}
      uses: actions/upload-artifact@v3
      with:
        name: slides-artifact
        path: ${{ inputs.path }}
