name: Publish GitHub Pages
on:
  push:
    branches:
      - main

jobs:
#  read_yaml:
#    runs-on: ubuntu-latest
#    name: Read slide configuration
#    steps:
#      - uses: actions/@checkout@v3
  # use this: https://github.com/marketplace/actions/yq-portable-yaml-processor

  slides:
    # This should definitely be abstracted, but for now just going
    # to hardcode each slide directory
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slideshow:
          - 2023-04-13_lab-meeting
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/spectacle
        with:
          path: ${{ matrix.slideshow }}


  jekyll:
    runs-on: ubuntu-latest
    needs: slides

    steps:
      - uses: actions/checkout@v3
      - name: Jekyll Cache
        uses: actions/cache@v3
        with:
          path: ./vendor/bundle
          key: ${{ runner.os }}-gemsv1-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gemsv1-
      - name: Download Slides Artifact
        uses: actions/download-artifact@v3
        with:
          name: slides-artifact
          path: site/
          # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: helaili/jekyll-action@2.4.0    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: "site"
